Payrol_Administration.Web/Models/AspNetUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payrol_Administration.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string theme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}

Payrol_Administration.Web/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Payrol_Administration.Web.Models;

namespace Payrol_Administration.Web.Controllers
{
    [Authorize(Roles = "Admin")]

    public class AspNetUsersController : Controller
    {
         
        private integratedDBEntities db = new integratedDBEntities();

        // GET: AspNetUsers

        public PartialViewResult EditPartial(string id)
                 
        {
           
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
           
           
            return PartialView(aspNetUser);
        }

        public ActionResult DetailsPartial(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            //---------------------------------------------------------------
            List<AspNetUser> only = new List<AspNetUser>();

            only = db.AspNetUsers.ToList();
            var extrae = from m in only where m.Id == id select m;
            ViewBag.List = extrae.ToList();

            //----------------------------------------------------------
            return View(aspNetUser);
        }
        public ActionResult Index()
        {
            List<AspNetUser> only = new List<AspNetUser>();
            only = db.AspNetUsers.ToList();
            var extrae = from m in only select m;
            ViewBag.List = extrae.ToList();

            return View(db.AspNetUsers.ToList());
        }

        // GET: AspNetUsers/Details/5

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            //---------------------------------------------------------------
            List<AspNetUser> only = new List<AspNetUser>();

            only = db.AspNetUsers.ToList();
            var extrae = from m in only where m.Id == id select m;
            ViewBag.List = extrae.ToList();

            //----------------------------------------------------------
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Photo")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Photo,File")] AspNetUser aspNetUser)
        {

            //-----------------------------------agrega foto-----------------------------
            if (aspNetUser.File == null) { return RedirectToAction("Index"); }

                if (aspNetUser.File.ContentLength > (2 * 1024 * 1024))
                {
                    ModelState.AddModelError("CustomError", "File size must be less than 2 MB");
                    return RedirectToAction("Index");
                }
                if (!(aspNetUser.File.ContentType == "image/jpeg" || aspNetUser.File.ContentType == "image/gif"))
                {
                    ModelState.AddModelError("CustomError", "File type allowed : jpeg and gif");
                    return RedirectToAction("Index");
                }
            
            //aspNetUser.FileName = aspNetUser.File.FileName;
            //aspNetUser.ImageSize = aspNetUser.File.ContentLength;

            byte[] data = new byte[aspNetUser.File.ContentLength];
            aspNetUser.File.InputStream.Read(data, 0, aspNetUser.File.ContentLength);

            aspNetUser.Photo = data;
            aspNetUser.UserName = aspNetUser.UserName;
            //using (ShieldEntities2 dc = new ShieldEntities2())
            //{
            //    dc.ImageGalleries.Add(IG);
            //    dc.SaveChanges();
            //}

            //--------------------------------------------------------------------------
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Payrol_Administration.Web/Views/AspNetUsers/Details.cshtml
@model Payrol_Administration.Web.Models.AspNetUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Payrol_Administration.Web.Models.AspNetUser> Lista = ViewBag.List;
}
<div class="page-container animated  fadeIn">
    <div class="page-content">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Details</h2>

                <div>
                    <h4>AspNetUser</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        @*<dt>

                                @Html.DisplayNameFor(model => model.Email)
                            </dt>*@
                        <dt>
                            @Html.DisplayFor(modelItem => modelItem.UserName)
                        </dt>


                        @*<dt>
                                @Html.DisplayNameFor(model => model.Photo)
                            </dt>*@

                        <dd>
                            <table>

                                @{
                                    int j = 0;
                                    for (int i = 0; i < Lista.Count(); i += 4)
                                    {
                                        j = i;
                                        <tr>
                                            @* I have done this for show 4 images in  a Row *@
                                            @while (j < i + 4 && j < Lista.Count())
                                            {
                                                <td>
                                                    <img src="data:image/png;base64,@Convert.ToBase64String(Lista[j].Photo,0,Lista[j].Photo.Length)" width="300" />
                                                </td>
                                                j++;
                                            }
                                        </tr>
                                    }
                                }
                            </table>
                            @*@Html.DisplayFor(model => model.Photo)*@
                        </dd>

                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>

        </div>
    </div>
</div>

Payrol_Administration.Web/Views/AspNetUsers/DetailsPartial.cshtml
@model Payrol_Administration.Web.Models.AspNetUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ScriptsVistaParcial.cshtml";
    List<Payrol_Administration.Web.Models.AspNetUser> Lista = ViewBag.List;
}

                <h2>Details</h2>

                <div>
                    <h4>AspNetUser</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        @*<dt>

                                @Html.DisplayNameFor(model => model.Email)
                            </dt>*@
                        <dt>
                            @Html.DisplayFor(modelItem => modelItem.UserName)
                        </dt>


                        @*<dt>
                                @Html.DisplayNameFor(model => model.Photo)
                            </dt>*@

                        <dd>
                            <table>

                                @{
                                    int j = 0;
                                    for (int i = 0; i < Lista.Count(); i += 4)
                                    {
                                        j = i;
                                        <tr>
                                            @* I have done this for show 4 images in  a Row *@
                                            @while (j < i + 4 && j < Lista.Count())
                                            {
                                                <td>
                                                    <img src="data:image/png;base64,@Convert.ToBase64String(Lista[j].Photo,0,Lista[j].Photo.Length)" width="500" />
                                                </td>
                                                j++;
                                            }
                                        </tr>
                                    }
                                }
                            </table>
                            @*@Html.DisplayFor(model => model.Photo)*@
                        </dd>

                    </dl>
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                    @Html.ActionLink("Back to List", "Index")
                </p>

Payrol_Administration.Web/Views/AspNetUsers/Edit.cshtml
@model Payrol_Administration.Web.Models.AspNetUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-container animated  fadeIn">
    <div class="page-content">
        <div class="panel panel-default">
            <div class="panel-body">

                <h2>Edit</h2>

                @* @using (Html.BeginForm())*@
                @using (Html.BeginForm("Edit", "AspNetUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>AspNetUser</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(Model => Model.File, new { type = "file" })
                                @Html.ValidationMessage("CustomError")
                                @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @Html.HiddenFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                                @*@Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @Html.HiddenFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                                @*@Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            @*@Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @*  @Html.HiddenFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })*@
                                @*@Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </div>
</div>

Payrol_Administration.Web/Views/AspNetUsers/EditPartial.cshtml
@model Payrol_Administration.Web.Models.AspNetUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/ScriptsVistaParcial.cshtml";
}


                @*<h2>Edit</h2>*@

                @* @using (Html.BeginForm())*@
                @using (Html.BeginForm("Edit", "AspNetUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @*<h4>AspNetUser</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(Model => Model.File, new { type = "file" })
                                @Html.ValidationMessage("CustomError")
                                @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @Html.HiddenFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                                @*@Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @Html.HiddenFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                                @*@Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            @*@Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <div class="col-md-10">
                                @*  @Html.HiddenFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })*@
                                @*@Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })*@
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
          

Payrol_Administration.Web/Views/AspNetUsers/Index.cshtml
@model IEnumerable<Payrol_Administration.Web.Models.AspNetUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Payrol_Administration.Web.Models.AspNetUser> photos = ViewBag.List;
}
<div class="page-container animated  fadeIn">
    <div class="page-content">
        <h2 aling="center">USER PHOTO</h2>

        @*------------------------Photo---------------------------*@

        <table class="table">

            @{
                int j = 0;

                for (int i = 0; i < photos.Count(); i += 4)
                {


                    j = i;
                    <tr>

                        @while (j < i + 4 && j < photos.Count())
                        {

                            <td>
                                <div class="col-md-12">
                                    <!-- CONTACT ITEM -->

                                    <div class="panel-body profile ">
                                        <div class="profile-image col-md-3">

                                            @if (photos[j].Photo != null)
                                            {

                                                @* I have done this for show 4 images in  a Row *@

                                                <img class="animated  flip" src="data:image/png;base64,@Convert.ToBase64String(photos[j].Photo, 0, photos[j].Photo.Length)" width="100" />




                                            }
                                            @if (photos[j].Photo == null)
                                            {

                                                <img class="animated  flip" src="~/Content/assets/images/users/SinImagen.jpg" alt="User" width="100" />

                                            }
                                        </div>
                                        <div class="profile-data">
                                            <div class="profile-data-name">@photos[j].UserName</div>
                                            <div class="profile-data-name"> </div>
                                        </div>
                                        @*<div class="profile-controls">
                                                <a href="#" class="profile-control-left"><span class="fa fa-info"></span></a>
                                                <a href="#" class="profile-control-right"><span class="fa fa-phone"></span></a>
                                            </div>*@
                                    </div>
                                    <div class="panel-body">
                                        <div class="contact-info" align="center">
                                            <h4><button id=@j class="btn btn-default btn-block" value=@photos[j].Id data-toggle="modal" data-target="#modal_large"><font color="#086A87"><b>CHANGE PHOTO</b></font></button></h4>
                                            @*<h4> @Html.ActionLink("Edit", "Edit", new { id = photos[j].Id }) </h4>*@
                                            @if (photos[j].Photo != null)
                                            {

                                                <h4> @Html.ActionLink("Details", "Details", new { id = photos[j].Id })</h4>

                                            }

                                            @*<p><small></small><br>(555) 555-55-55</p>
                                                <p><small>Email</small><br>nadiaali@domain.com</p>
                                                <p><small>Address</small><br>123 45 Street San Francisco, CA, USA</p>*@
                                        </div>
                                    </div>
                                </div>

                            </td>

                            j++;
                            @*@Html.Hidden("ValorJ", new { value = j, id = "ValorJ" });*@
                        }

                        <!-- END CONTACT ITEM -->

                    </tr>
                }
            }

        </table>
        @*-----------------------modal 1----------------*@
        <div class="modal" id="modal_large" tabindex="-1" role="dialog" aria-labelledby="largeModalHead" aria-hidden="true">
            <div class="modal-dialog modal-lg" id="minimodal">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="largeModalHead">Change Photo User</h4>
                    </div>
                    <div class="modal-body">
                        @*---------------------------------tabs-----------------------------*@





                        <div id="editaresultado">1</div>





                        @*---------------------------------End tabs-----------------------------*@






                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="CerrarModal">Close</button>
                    </div>
                </div>
            </div>

        </div>
        @*-----------------------modal 2----------------*@
        <div class="modal" id="modal_large2" tabindex="-1" role="dialog" aria-labelledby="largeModalHead" aria-hidden="true">
            <div class="modal-dialog modal-lg" id="minimodal">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="largeModalHead">xfvcdcvsdcvsd</h4>
                    </div>
                    <div class="modal-body">
                        @*---------------------------------tabs-----------------------------*@





                        <div id="Detalles">2</div>





                        @*---------------------------------End tabs-----------------------------*@






                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="CerrarModal">Close</button>
                    </div>
                </div>
            </div>

        </div>
        @*<h4><button id="Editando" class="btn btn-default btn-block" value=@photos[0].Id data-toggle="modal" data-target="#modal_large">EDIT</button></h4>*@
    </div>
</div>
   





<script type="text/javascript">
    $(document).ready(function () {


        for (var i = 0; i < 100 ; i++) {
            if (i < 100) {
                document.getElementById(i).addEventListener("click", function () {

                    $('#modal_large').addClass('animated  fadeInUpBig');

                    var PhotoId = $(this).val();
                    //document.getElementById("machine").innerHTML = "Machine # " + PrductoId;


                    var URL = '../AspNetUsers/EditPartial?id=' + PhotoId;
                    //document.getElementById("ChangeMachine").value = PrductoId;

                    $.ajax({
                        url: URL,
                        contentType: 'application/html; charset=utf-8',
                        type: 'GET',
                        datatype: 'html'
                    })
                    .success(function (result) {

                        $('#editaresultado').html(result);

                    })
                });
            }

        }
    });
</script>